image: dockerfile/nodejs
git:
    path: github.com/jbydeley/angular-todo-tutorial
script:
    - npm install
    - npm install -g bower
    - npm install -g grunt-cli
    - bower install
    - grunt test

